version: 2.1

orbs:
  codacy: codacy/base@0.3.7

workflows:
  compile_test_deploy:
    jobs:
      - codacy/checkout_and_version
      - codacy/shell:
          name: build
          context: CodacyAWS
          cmd: ./gradlew build
          requires:
            - codacy/checkout_and_version
          filters:
            branches:
              ignore:
                - master
      - codacy/shell:
          name: build-and-publish-2_12
          context: CodacyAWS
          cmd: |
            export VERSION="$(cat .version)"
            # export SCALA_VERSION="2.12.9"
            ./gradlew build publishToSonatype getStagingProfile closeAndReleaseRepository --stacktrace
          requires:
            - codacy/checkout_and_version
            - build-and-publish-2_11
          filters:
            branches:
              only:
                - master
      - codacy/shell:
          name: build-and-publish-2_11
          context: CodacyAWS
          cmd: |
            export VERSION="$(cat .version)"
            export SCALA_VERSION="2.11.12"
            ./gradlew build publishToSonatype getStagingProfile closeAndReleaseRepository --stacktrace
          requires:
            - codacy/checkout_and_version
          filters:
            branches:
              only:
                - master
      - codacy/tag_version:
          name: tag_version
          context: CodacyAWS
          requires:
            - build-and-publish-2_12
          filters:
            branches:
              only:
                - master
