version: 2.1

orbs:
  codacy: codacy/base@11.0.0

workflows:
  compile_test_deploy:
    jobs:
      - codacy/checkout_and_version:
          write_sbt_version: true
      - codacy/sbt:
          name: compile
          cmd: sbt +compile
          persist_to_workspace: true
          requires:
            - codacy/checkout_and_version
      - publish_dev_approval:
          type: approval
          requires:
            - compile
          filters:
            branches:
              ignore:
                - master
      - codacy/sbt:
          name: publish_dev
          context: CodacyAWS
          aws_profile: maven
          steps:
            - run:
                name: Publish to internal S3
                command: |
                  echo 'privateMvnPublish' > publishing.sbt
                  sbt +publish
          requires:
            - publish_dev_approval

      - codacy/sbt:
          name: publish_lib
          cmd: |
            echo 'publicMvnPublish' > sonatype.sbt
            sbt retrieveGPGKeys +publishSigned sonatypeCentralRelease
          context: CodacyAWS
          requires:
            - compile
          filters:
            branches:
              only:
                - master
      - codacy/tag_version:
          name: tag_version
          context: CodacyAWS
          requires:
            - publish_lib
