version: 2.1

orbs:
  codacy: codacy/base@2.1.0

workflows:
  compile_test_deploy:
    jobs:
      - codacy/checkout_and_version
      - codacy/shell:
          name: build
          context: CodacyAWS
          cmd: ./gradlew build
          requires:
            - codacy/checkout_and_version
      - codacy/tag_version:
          name: tag_version
          context: CodacyAWS
          requires:
            - build
          filters:
            branches:
              only:
                - master
                - allow-pagination-list-memberships
      - codacy/shell:
          name: publish
          context: CodacyAWS
          cmd: |
            export VERSION="$(cat .version)"
            # export SCALA_VERSION="2.12.9"
            ./gradlew build publishToSonatype getStagingProfile closeAndReleaseRepository
            export SCALA_VERSION="2.11.12"
            ./gradlew build publishToSonatype getStagingProfile closeAndReleaseRepository
          requires:
            - tag_version
