version: 2.1

orbs:
  codacy: codacy/base@5.2.0

workflows:
  compile_test_deploy:
    jobs:
      - codacy/checkout_and_version:
          write_sbt_version: true
      - codacy/sbt:
          name: compile
          cmd: sbt +compile
          persist_to_workspace: true
          requires:
            - codacy/checkout_and_version
      - codacy/sbt:
          name: publish_lib
          cmd: sbt retrieveGPGKeys +publishSigned sonatypeBundleRelease
          context: CodacyAWS
          requires:
            - compile
      - codacy/tag_version:
          name: tag_version
          context: CodacyAWS
          requires:
            - publish_lib
